### PR TITLE
No more custom dataframes

### PR DESCRIPTION
**Pull request by moeyensj**
This PR removes all the custom to/from_dataframe methods -- feels so much cleaner not to override what quivr is doing. 

These tests will fail until we get a fix in for #71.

### CODE REVIEW

**Comment by moeyensj** [comment]
I've modified the Observer states test data to be stored as parquet files as well with null-filled covariances. This allows the unit tests to pass for those functions.

Despite having removed the custom dataframes for Timestamp, I am still getting errors for the dataframe roundtripping.

**Comment by moeyensj** [comment]
The error I'm getting on the last timestamp round trip test is the following: 
```python
kwargs = {'scale': 'tdb'}, name = 'scale', value = 'tdb'

    def __init__(self, table: pa.Table, **kwargs: AttributeValueType):
        self.table = table
        for name, value in kwargs.items():
            if name in self._quivr_attributes:
                setattr(self, name, value)
            else:
>               raise AttributeError(f"{self.__class__.__name__} has no attribute {name}")
E               AttributeError: Wrapper has no attribute scale

../quivr/quivr/tables.py:138: AttributeError
```
Looks like attributes are not passed down to nested tables when using from_flat_dataframe? Is this the correct behavior?

I definitely like the idea of trying out dataframe attributes as a way to persist quivr attributes.

**Comment by spenczar** [comment]
Correct, dataframes do not store attributes, so they won't round-trip.

`to_csv` has special behavior for this, which should perhaps be ported over to the dataframes: https://github.com/spenczar/quivr/blob/main/quivr/tables.py#L875-L880

**Comment by moeyensj** [comment]
Thanks for doing that, I'll re-mark the pytest as an expected failure for the time being.

**Comment by spenczar** [comment]
The dataframes should preserve attributes as of quivr v0.7.0a3. Maybe its time to release 0.7.0 though.

**Comment by moeyensj** [comment]
@spenczar Unit tests pass with the pre-release version (https://github.com/B612-Asteroid-Institute/adam_core/pull/72/commits/7a8a6b775c64cb336a14b6c1f0519b72b60c3755). Thanks for getting dataframe attributes implemented.

I can get [the sort_by PR](https://github.com/spenczar/quivr/pull/54) review comments addressed in the next few hours if you would rather wait to roll that into 0.7.0. No preference on my side.

**Pull request merged**
